# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-24 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modern_cv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
