# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-24 17:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modern_cv', '0002_auto_20180324_2346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='status',
            new_name='is_active',
        ),
    ]
