# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-26 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modern_cv', '0004_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, max_length=75, upload_to=''),
        ),
    ]
