# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-28 08:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modern_cv', '0006_auto_20180328_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='big_image',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='small_image',
        ),
    ]
